### ISSUE TITLE
Can't access map_array: TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by pahp** [UMDCYL/pac-bot#37]
I tried to add in the map_array[][] using the code that worked for Space Invaders, but when I touch map_array in bot code, I get the following errors:

```
Traceback (most recent call last):
  File "/home/pedro/src/CYLGame/CYLGame/Server.py", line 242, in sim
    gtoken = runner.run(room, playback=True).save(self.gamedb)
  File "/home/pedro/src/CYLGame/CYLGame/Game.py", line 308, in run
    player.run_turn(game.random)
  File "/home/pedro/src/CYLGame/CYLGame/Player.py", line 55, in run_turn
    nxt_state = self.prog.run(self.get_state(), max_op_count=max_ops, random=random)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 279, in run
    self.handle(self.ast, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 267, in handle
    return handler(node, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 188, in handle_block
    self.handle(child, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 267, in handle
    return handler(node, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 183, in handle_assign
    sym_tbl[node.left.value] = self.handle(node.right, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 267, in handle
    return handler(node, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 219, in handle_getarrayitem
    var = self.handle(node.left, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 267, in handle
    return handler(node, sym_tbl)
  File "/home/pedro/.local/share/virtualenvs/pac-bot-CuEVk7J3/lib/python3.6/site-packages/littlepython/interpreter.py", line 220, in handle_getarrayitem
    return var[self.handle(node.right, sym_tbl)]
TypeError: 'int' object is not subscriptable
```

**Comment by pahp** [comment]
The bot code in question was

```
foo = map_array[0][0]
```

**Comment by pahp** [comment]
I have punted this issue for now -- I just removed map_array from the code (commented it out) and removed it from the documentation. The game should be playable without the map.
